### PR TITLE
Fix android uwp32 build

### PR DESCRIPTION
**Pull request by AnisB**
###### Description:
Fixing android and uwp32 builds

### CODE REVIEW

**Comment by AnisB** [comment]
@spufriendly @jschmidt42

**Review by void-etoile — CHANGES_REQUESTED** [review]
This is absolutely not your fault but let's take this opportunity to clean CMakeSettings.cmake properly.  There are loads of things in there that should not be (e.g. use Nav, use HIK, use Sound) - I'd say about 80% of that you can get rid of.

**Comment by AnisB** [comment]
@spufriendly willdo

**Review by void-etoile — APPROVED** [review]
Looks good!

**Review by jschmidt42 — COMMENTED** [review]
Actually those were kept so merges from the main repo are easier to do. The cleanup should first be done in the main repo.

**Comment by jschmidt42** [comment]
Hi @spufriendly, the reason the cmake scripts contains a lot of "unneeded" stuff is too keep them in sync with the one in the main stingray repo so it is easier to merge them later.

**Comment by jschmidt42** [comment]
@AnisB thank you for the fix.

**Pull request merged**
